# Generated by Django 3.2.2 on 2021-05-18 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0002_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='client_id',
        ),
        migrations.AddField(
            model_name='contract',
            name='profile_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
