# Generated by Django 3.2.2 on 2021-05-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20210518_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.carclass'),
        ),
        migrations.AlterField(
            model_name='car',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.location'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.cartype'),
        ),
    ]
