# Generated by Django 3.2.2 on 2021-05-20 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("viewer", "0004_auto_20210520_1601"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="car_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="viewer.car"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="profile_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
