# Generated by Django 3.2.2 on 2021-05-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_auto_20210526_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
