# Generated by Django 3.2.2 on 2021-05-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210517_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
